### PR TITLE
Use /content FP directory for overlaying, simplify the integrated FP

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@objectiser could you please review and eventually merge?

**Comment by ppalaga** [comment]
@objectiser please, hold on, I found one litte problem here when testing in HK main.

**Comment by objectiser** [comment]
ok will hold off

**Comment by objectiser** [comment]
@ppalaga when sorted, is there a branch of main that I can test the btm feature pack against?

**Comment by ppalaga** [comment]
In 5110529 the missing resources like `elasticsearch.properies` and `setenv.sh` were added back.

5110529 can be tested against https://github.com/hawkular/hawkular/pull/872

**Comment by objectiser** [comment]
Changes look fine - in the process of building/testing.

**Comment by objectiser** [comment]
Thanks Peter - much better :+1:

**Pull request merged**
