### PR TITLE
Take the subsystems.xml and template.xml unchanged or transformed from the depen

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@objectiser this PR shows the idea of extending the subsystems.xml and template.xml from the dependency feature packs.

Note that the present PR depends on https://github.com/hawkular/hawkular-accounts/pull/137 and will fail untill https://github.com/hawkular/hawkular-accounts/pull/137 is merged or you can try it out locally with `-Dsrcdeps.url.1.accounts=scm:git:https://github.com/ppalaga/hawkular-accounts.git`

I did the changes only for your standalone feature pack. The integrated FP is TBD.

**Comment by objectiser** [comment]
@ppalaga  Ok thanks Peter - when is the accounts change going to be merged?

**Comment by objectiser** [comment]
Tested locally and it worked fine. Restarted travis build.

**Comment by jpkrohling** [comment]
The Accounts change is merged. A new release will follow probably today.

**Comment by objectiser** [comment]
Seems to be a problem running the srcdeps in travis:
 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-ear-plugin:2.10.1:ear (default-ear) on project hawkular-commons-embedded-cassandra-ear: Error assembling EAR: Problem creating jar: Execution exception: Java heap space -> [Help 1]

I'll merge as worked locally.

**Pull request merged**
