### PR TITLE
HWKBTM-350 & HWKBTM-351 Prop/Fault Filtering @ SB

### PR DESCRIPTION
**Pull request by ammendonca**
Initial commit for adding property and failt filtering to the sidebar.
This enables the APM and DT tabs to be make use of it.

### CODE REVIEW

**Comment by ammendonca** [comment]
@objectiser, please have a look at this first implementation, and let me know wdyt.
Currently retrieving Properties from server only has results after selecting one of the BTxns.. not sure this is an intended limitation. Faults work without any selected BTxn.

**Comment by objectiser** [comment]
@ammendonca Looks and works great - only found one issue, when viewing data with a couple of 'contact' properties set to exclusion, when I changed one to be inclusion the values available in the typeahead field was not updated - it kept the same values as before the exclusion/inclusion change.

**Comment by objectiser** [comment]
Actually I will merge, and this can be fixed as a separate issue - I'll make sure the properties are not dependent on the business transaction name being specified.

**Comment by objectiser** [comment]
@ammendonca I've created HWKBTM-437 regarding the properties only being returned for business transactions. I think this needs more thought, to sort out the REST API, so would it be possible (for now) to just disable the property selection if no business transaction is selected? This wouldn't be the long term solution, but just for this next release.

**Comment by ammendonca** [comment]
@objectiser, thanks for merging. I've replicated the problem you've mentioned, will work on a fix for it.
Regarding disabling the property selection, indeed it makes sense, actually at any point where there are no options, it should be disabled.

Just a side note, the look of the dropdowns should be more integrated with the '+', '-' buttons, as it should be grey (like the time span dropdown), but there seems to be an issue with the pf-select directive, something to investigate further.

**Comment by objectiser** [comment]
@ammendonca ok no problem, if can't be sorted now just create a jira so we can revisit in the future.

**Pull request merged**
