### PR TITLE
Distributed Tracing Enhancements

### PR DESCRIPTION
**Pull request by ammendonca**

### CODE REVIEW

**Comment by objectiser** [comment]
Looks great, but a couple of suggestions, which could be handled in a separate PR if you want (let me know if you would prefer this merged first):

1) Can you default the distributed tracing graph to the first node, so it is not blank if there is some possible content.

2) Time span - can you default it to 1 hour, so is the same as the other pages (I know this means changing each time for the test data, but in general it would show something recent).

3) There doesn't appear to be a refresh cycle, could it be added so is the same as the other pages.

**Comment by ammendonca** [comment]
Thanks for the feedback. I will address all of them in this PR, but 3) should be covered with https://github.com/hawkular/hawkular-btm/pull/384/commits/884a0eecf602e2cd54b6e594a476d5a3dd53f713#diff-0299e42f6d476fcc11e0f677f70d1b49R59 . are you not seeing it update the data or the graph itself ?

**Comment by objectiser** [comment]
I initially loaded the test data, viewed the graph (third one), then ran the actual example to generate some more data, so it wouldn't have changed the structure itself - but didn't see any of the numbers change. So I refreshed the browser, had to select the third node again, and this time it showed the updated numbers.

**Comment by objectiser** [comment]
Would it be possible to add the following functionality - if the count field is missing on a node and/or link, can you just display it in grey (i.e. like it is disabled), without any duration/avg info (no tooltip)?

Reason being that while trying to sort out the property filtering issue, and even as part of the solution, I thought it might be good to have a completion representation of the business txn structure, and then have enabled nodes/links (with metrics/tooltips) for those nodes/links associated with the property.

So if a node/link has no count/avg, etc, it is like it is a placeholder.

**Comment by ammendonca** [comment]
Yes, that looks like good a way to have it (was thinking of something a bit more transparent and/or with dashed line), to make it noticeable that it is filtered out and just present as a placeholder.

**Comment by objectiser** [comment]
Ok I will work on returning the graph using this approach. The associated issue is hwkbtm 410.

**Comment by ammendonca** [comment]
Updated having fixed the mentioned issues. There's a known issue (zoom/position resets on update), will work on that.

**Comment by objectiser** [comment]
Thanks Alexandre, great work again!

**Pull request merged**
