### PR TITLE
HAWKULAR-585 - Updated Accounts - Cassandra datastore

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by objectiser** [comment]
NOTE: Should not be merged currently until final release.

Couple of issues found (for future reference):
- server war needs to include (or reference) cassandra datastax driver
- getting a "java.lang.RuntimeException: Unable to resolve realm public key remotely" exception in the server console after starting the server, when attempting to access the BTM UI from a browser

**Comment by jpkrohling** [comment]
Example of how to specify the dependency on the driver: 
https://github.com/hawkular/hawkular-accounts/blob/master/accounts/pom.xml#L146

**Comment by jpkrohling** [comment]
Another option is to use jboss-deployment-structure.xml .

**Comment by objectiser** [comment]
All integration tests worked with cassandra driver. Just need to sort out issue with auth URL when using port offset.

**Pull request closed without merging**
