### PR TITLE
UI Improvements to better align with Hawkular

### PR DESCRIPTION
**Pull request by ammendonca**

### CODE REVIEW

**Comment by objectiser** [comment]
Processing....

**Comment by objectiser** [comment]
Couple of issues in standalone:
1) The header part of the box per business txn on the btm (Managed) page is small and there is a gap between the header and the part with the numbers.
2) When first going onto the Managed page, or when doing a refresh on that page, the pie chart is blank until the first refresh - although the legend is present.

Will check integrated version now.

**Comment by objectiser** [comment]
In integrated version, the same problems occurred - also on first refresh the legend disappeared until the second refresh where the pie chart resized to include the legend. Not sure if this also happened on standalone.

I'll merge to enable further work on the html, so can be handled in separate PRs.

**Comment by objectiser** [comment]
Thanks Alexandre!

**Comment by ammendonca** [comment]
OK. This is a non-finished version, it was for passing it over to @cardosogabriel for proceeding with visual enhancements. After switching to Hawkular LESS file the problem 1) occurred, it is likely missing some class. 2) I haven't observed but will review. Thanks!

**Comment by objectiser** [comment]
Ok thanks - I've created https://issues.jboss.org/browse/HWKBTM-333 for the two issues.

**Pull request merged**
