### PR TITLE
HWKBTM-333 : Fix pie chart not displaying at first

### PR DESCRIPTION
**Pull request by ammendonca**
This fixes the pie chart not showing and resizing to several forms. This
is due to non-angular lib with angular hide/show of parent element. An
extra variable is observed to know that data is already available.

### CODE REVIEW

**Comment by objectiser** [comment]
Looks like this branch has conflicts now, possibly due to the changes I merged for Gabriel. Would you be able to take a quick look?

**Comment by objectiser** [comment]
Think it was a simple conflict, so just testing.....

**Comment by objectiser** [comment]
After fixing conflict in btm.html, I got:

TypeError: Cannot read property 'load' of undefined
    at Scope.n.reloadTxnCountGraph (http://localhost:8180/dist/hawkularbtm.js:1:8113)
    at fn (eval at <anonymous> (http://localhost:8180/libs/angular/angular.js?v=1456258545231:13231:15), <anonymous>:4:248)
    at Scope.$eval (http://localhost:8180/libs/angular/angular.js?v=1456258545231:15916:28)
    at pre (http://localhost:8180/libs/angular/angular.js?v=1456258545231:24314:15)
    at invokeLinkFn (http://localhost:8180/libs/angular/angular.js?v=1456258545231:8746:9)
    at nodeLinkFn (http://localhost:8180/libs/angular/angular.js?v=1456258545231:8225:11)
    at compositeLinkFn (http://localhost:8180/libs/angular/angular.js?v=1456258545231:7637:13)
    at compositeLinkFn (http://localhost:8180/libs/angular/angular.js?v=1456258545231:7641:13)
    at nodeLinkFn (http://localhost:8180/libs/angular/angular.js?v=1456258545231:8241:24)
    at compositeLinkFn (http://localhost:8180/libs/angular/angular.js?v=1456258545231:7637:13) <div id="btxntxncountpiechart" style="height: 250px;" ng-init="reloadTxnCountGraph()">

**Comment by ammendonca** [comment]
I will rebase the branch and retry

**Comment by objectiser** [comment]
Thanks Alexandre!

**Pull request merged**
