### PR TITLE
Add min/max date to Datetime Pickers + Enhancements

### PR DESCRIPTION
**Pull request by ammendonca**

### CODE REVIEW

**Comment by objectiser** [comment]
@ammendonca Experienced some issues:

1) On fresh start with no data, tried the custom button and then went back to time span 1hr
2) Started the make-bookings.sh script and left for a couple of minutes before then selecting the custom button again
3) It immediate resulted in no data being shown, and on inspection I saw the custom end date/time was set to when I had started up the UI (or possible selected the custom button before), rather than the current time when I selected the custom button
4) I then selected the calendar symbol on the end time and immediately (without selecting a value) data appeared - but noticed that the year had been set to 2023.
5) Also whenever the calendar button is pressed (just to show the calendar) it changes the value in the text field without any details being changed.

**Comment by objectiser** [comment]
Was able to reproduce again from a refresh start - this time did the steps spread out to find more info.

When selecting the custom option for the second time, it set the start/end date/time to the minute when the custom option was selected the first time, so looks like those values are cached somehow.

Same behaviour on the calendar icon for the end time - when first pressed (after selecting custom for the second time) it jumps to 2023, then back to 2020 and decrements an hour each time it is pressed.

**Comment by ammendonca** [comment]
Thanks for the feedback. This is odd. I can't replicate the behavior (with data, will need to clean data for no data experiments), but seems there's some issue with locales since being the 23rd and the year being set to 2023 doesn't seem like a coincidence.

Whenever I click the calendar nothing happens (ie, nothing changes) and I'm able to select everything properly.

The only _issue_ I can reproduce is when going back to preset time span and then setting a custom, it still has the custom from before. Not sure this is something we want to fix or not.. might be handy to keep the last set value instead of setting to the same time span the preset had (which is the initial behavior).

Will try to reproduce other issues.

**Comment by objectiser** [comment]
I'd prefer that the custom values are initialised based on the timespan currently being viewed prior to selecting custom, otherwise the data suddenly changes and it appears something strange has happened - which is why I picked up on it in the first place.

It is better if the custom initial values are end=current time, and start is derived based on timespan, so that it has the effective of essentially freezing the data, until the user can then decide how they wish to change the start/end dates by hand.

**Comment by ammendonca** [comment]
OK; changed the initial behavior to be the default in all situations.

Since it seems the format was causing the problems, for now will disable the custom format and go with default. Please let me know how it works now.

**Comment by objectiser** [comment]
Thanks Alexandre! That worked great. Unfortunately it means there is the issue with precision as not possible to select seconds at the moment, so would be good to revisit that in a future release.

**Pull request merged**
