### PR TITLE
HWKBTM-422 : Add fine grained time control with Datetime Picker

### PR DESCRIPTION
**Pull request by ammendonca**

### CODE REVIEW

**Comment by objectiser** [comment]
@ammendonca Thanks for this, it looks really good and the UI works well. Just found a couple of issues:

1) The build fails because the datetime-picker.less needs a license header

2) I used the make-bookings.sh script to load a couple of minutes of data, and then found:

a) if the start and end custom date/time are set to the same value (i.e. minute) no data is shown, although if either is changed up or down one minute, then the data appears with timestamps showing it was in the correct time range.  Does the end time for a particular minute include the 59 seconds, to pickup the end of that minute?

b) noticed when selecting custom timespan, the resume button appears - but if selected it does nothing, so possibly it should be disabled and possibly have different text?

c) when I changed the timespan back to 1 hour, the pause/resume button changed back to the 'pause' state which is fine, but then when I pressed the button it didn't do anything.

btw these were all on the APM page - didn't try it on DT yet.

**Comment by ammendonca** [comment]
Thanks for the feedback, @objectiser.

Regarding 2a), I don't think it is including 59 seconds, so not sure what makes it work like that. Anyway, I've tried having it so that the end time picker would only accept date/time greater than the start time. Haven't yet got it to work properly.

For 2b) and 2c) I agree it should be disabled and will have a look at what's making it not work after having a custom time span.. I've made some adjustments for it to work with the custom time span, but maybe in the last changes I didn't tested it fully.

On DT page it should be the same.. except it doesn't have the Pause/Resume Live Data (which it probably should?)

**Comment by objectiser** [comment]
@ammendonca I guess the DT page should have the pause/resume button as well - wonder if it should be by the timespan in the filter panel?

**Comment by objectiser** [comment]
Or could just place the button alongside the 'reset zoom' button on DT page for now.

**Comment by objectiser** [comment]
Thanks, great work Alexandre!

**Pull request merged**
